#!/bin/sh

INSTANCE="${1:-BAT0}"
ALERT_LOW="${2:-10}"

if test -e "/sys/class/power_supply/$INSTANCE"
then
    status=$(cat /sys/class/power_supply/$INSTANCE/status)
    capacity=$(cat /sys/class/power_supply/$INSTANCE/capacity)
	if [ $capacity -gt 89 ]
	then
		baticon="\uf240"
	else
		if [ $capacity -gt 62 ]
		then
		baticon="\uf241"
		else
			if [ $capacity -gt 35 ]
			then
				baticon="\uf242"
			else
				if [ $capacity -gt 10 ]
				then
					baticon="\uf243"
				else
					baticon="\uf244"
				fi
			fi
		fi
	fi
    case "$status" in
        "Discharging")
            symbol=''
			remaining="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "time" | cut -d ' ' -f 14-15)"
			#remaining="$(acpi)"
            ;;
        "Charging")
            symbol=''
			remaining="Charging"
            ;;
        "Full")
			remaining="Full"
            ;;
    esac

    # Full text
	#echo "$baticon $capacity%"
	echo -n "%{T2}$baticon %{T-} $capacity% $remaining"
    # Short text
    #echo "Ψ $capacity% $symbol"

    # Color
    #if test $capacity -le $ALERT_LOW -a $status = "Discharging"
    #then
        #echo "#F5A3A3"
    #fi
	#if [ $status = "Charging" ]
	#then
		#echo "#70CBB6"
	#fi
fi
