#!/bin/sh

text=''

for INTERFACE in $(ls /sys/class/net/); do
    state="$(cat /sys/class/net/$INTERFACE/operstate)"
    if [ "$state" = "up" ]; then
        ipaddr="$(ip addr show $INTERFACE | perl -n -e'/inet (.+)\// && print $1')"
        ipaddr="${ipaddr:- -}"
		iwid="$(iwgetid -r)"

		if [ "$INTERFACE" = "wlp8s0" ]; then
			text="\uf1eb  $iwid $ipaddr"
		else
			text="\uf0e8  $ipaddr"
		fi
    fi
	if [ "$INTERFACE" = "bnep0" ]; then
		if [ "$(ls -A /sys/class/net/$INTERFACE)" ]; then
			text=" Bluetooth network"
		fi
	fi
done

if [ -n "$text" ]; then
    echo "${text}"
else
    echo "    No connection"
fi